version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.5.9
    container_name: artifactory
    ports:
     - 127.0.0.1:8081:8081
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory
     - /docker/tomcat/server.xml:/opt/jfrog/artifactory/tomcat/conf/server.xml
    environment:
     - EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    container_name: artifactory
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/vhost/artifactory.conf:/etc/nginx/conf.d/default.conf
      - /docker/nginx/cert/wajatmaka.com.crt:/etc/nginx/wajatmaka.com.crt
      - /docker/nginx/cert/wajatmaka.com.key:/etc/nginx/wajatmaka.com.key
      - /data/nginx/logs:/var/log/nginx
volumes:
  artifactory:
  logs:
  opt:

